### ISSUE TITLE
Assets are not resolved selectively

### ISSUE THREAD

**Issue by t-kamyk** [contentful/contentful.net#288]
Hi!

I have an issue regarding the resolution of assets included in two different content items.

Consider the following model - the content type contains an asset field (MainImage) and a Rich text field (RtfBody):

```public class CMSArticle : IContent
{
    public string Id { get; set; }
    public string Headline { get; set; }
    public string IntroParagraph { get; set; }
    public Asset MainImage { get; set; }
    public Document RtfBody { get; set; }
}
```

The RtfBody contains a link to another content item.

If contentA contains a link to contentB and contentA is published after contentB, the MainImage of contentB will be resolved to `null`.

contentA:

![image](https://user-images.githubusercontent.com/102153598/159470530-1a81c55c-214f-4123-b372-8fd3a0a5b67c.png)

contentB:

![image](https://user-images.githubusercontent.com/102153598/159470668-b6d4620a-c8fa-42e1-9a14-568870db13a2.png)

The serialized result of the query:

```[
  {
    "Id": "[Redacted]",
    "Headline": "Test article 2",
    "IntroParagraph": "Test intro paragraph 2",
    "RtfBody": {
      "NodeType": "document",
      "Data": { "Target": null },
      "Content": [{}]
    },
    "MainImage": {
      "SystemProperties": {
        "Id": "[CorrectId]",
        "LinkType": null,
        "Type": "Asset",
        "Revision": 1,
        "Version": null,
        "CreatedAt": "2022-03-22T09:56:26.691Z",
        "UpdatedAt": "2022-03-22T09:56:26.691Z",
        "ContentType": null,
        ...
      },
      "Title": "test_2",
      "File": {
        "FileName": "pexels-juan-salamanca-61143.jpg",
        "ContentType": "image/jpeg",
        "Url": "[CorrectUrl]",
        "UploadUrl": null,
        "UploadReference": null,
        "Details": {
          "Size": 2003506,
          "Image": { "Height": 3456, "Width": 5184 }
        }
      },
      ...
    },
    ...
  },
  {
    "Id": "[Redacted]",
    "Headline": "Test article 1",
    "IntroParagraph": "Test intro paragraph 1",
    "RtfBody": {
      "NodeType": "document",
      "Data": { "Target": null },
      "Content": [{}]
    },
    "MainImage": null,
    ...
  }
]
```

The issue seem to be similar for Entries and can be resolved using the `ResolveEntriesSelectively` flag, but it does NOT work for Assets in the same scenario.

That's because of the `&& linkToken["linkType"]?.ToString() != "Asset"` condition in the following code in `CmsClient.cs`

```
if (replacementToken != null)
                {
                    grandParent.RemoveAll();
                    grandParent.Add(replacementToken.Children());
                    PropertyInfo prop = null;

                    if (ResolveEntriesSelectively)
                    {
                        prop = type?.GetRuntimeProperties().FirstOrDefault(p => (p.Name.Equals(propName, StringComparison.OrdinalIgnoreCase) ||
                            p.GetCustomAttribute<JsonPropertyAttribute>()?.PropertyName == propName));
                        if (prop == null && linkToken["linkType"]?.ToString() != "Asset")
                        {
                            //the property does not exist in the entry. Skip it in resolving references.
                            continue;
                        }
                    }
```

Is there a specific reason for this condition?

If not, then can it be fixed by simply removing it?
If yes, what is it and can it be fixed by adding a new `ResolveAssetsSelectively` flag to the options?

I'm open to submitting a PR as soon as I can get this insight

**Comment by Roblinde** [comment]
hmm, the idea is that assets shouldn't have to be resolved selectively since we always know what class to deserialize them into. The entry that is contained within the RtfBody, what does it resolve into? If it resolves into a class that contains the image then I would expect this to work, if not then that is probably the easiest solution. 

I'm currently looking into improving the deserialization of rich text further, not sure when I will have the time to release and update though.

**Comment by t-kamyk** [comment]
We are actually using the built-in Document type for deserialization - you can see it on the model above.

However, it seems that an Entry link is resolved differently for two different content items.

For contentA:
![cont_1](https://user-images.githubusercontent.com/102153598/159498088-8d23301d-2b06-4d40-98bb-4ba599caeaf0.PNG)

For contentB:
![cont_2](https://user-images.githubusercontent.com/102153598/159498133-7897f680-9ea4-4c43-bade-671b6b4cc0a7.PNG)

**Comment by t-kamyk** [comment]
No, they point to two completely different assets.

The connection between these two is an entry link placed in the RtfBody - contentA has an entry link to contentB and vice versa.

**Comment by t-kamyk** [comment]
To match the screenshots:

item[0] (Test article 1) has a link in the RtfBody to item[1] (Test article 2) and vice versa.

The collection is sorted by default by Contentful API, by publish date.

**Comment by Roblinde** [comment]
ah I see, do you see that contentA has the EntryStructure turned into a `CustomNode`. Do you have a ContentTypeResolver setup for the project? 

What happens, and this is so annoying with the rich text structure is that one entry that contains links to other assets and entries potentially, is not resolved to a strong type, but instead turned into the `CustomNode`, this in turn uses a Json.Net `JObject` to store the actual json data of the reference. Unfortunately json.Net does not resolve references within `JObject` or `dynamic` only strongly typed classes.

**Comment by t-kamyk** [comment]
No we don't have the ContentTypeResolver setup.

Is the solution to set it up to map the `entry-hyperlink` to our `CmsArticle` type?

**Comment by Roblinde** [comment]
Yeah, I think this will be resolved by setting up a ContentTypeResolver, bascially instructing the serializer how a certain content type should be handled. This will make sure it can be deserialized correctly even if it's part of a rich text structure.

**Comment by t-kamyk** [comment]
Implementing the suggestion and testing. It seems to work great, but I'll update you once again when we finish the testing.

Thanks for the help!
